server:
  port: 8888
mybatis-plus:
  # --告诉 Mapper 所对应的 XML 文件位置。
  mapperLocations: classpath:/mapper/**/*.xml
  # --别名，被扫描的包resultType可以直接用类名，而不是全限定的类名.....typeAliasesSuperType
  #  typeAliasesPackage: "/com/it/pojo"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # --开启sql日志
    # --该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性，mp默认true
    map-underscore-to-camel-case: true
    cacheEnabled: false # --二级缓存，默认开启。如果分页失效试试关闭
  global-config:
    # --设置pojo与数据库表对应
    dbConfig:
      #      id-type: auto             # --全局默认主键类型，auto等同于主键默认添加@TableId(type = IdType.AUTO)
      tablePrefix: tb_          # --全局表名前缀
#      logic-delete-field: flag  # --全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1     # --逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # --逻辑未删除值(默认为 0)
spring:
  application:
    name: breeze-server
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
            enabled: true
  servlet:
    multipart: #配置文件上传
      enabled: false
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严格型检查 默认是html 严格检查
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_breeze?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root